---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-data-volume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-ceph-ssd-ms1

