FROM python:3.9-slim-buster
WORKDIR /python-docker
COPY . .
RUN pip3 install -r requirements.txt --trusted-host pypi.org --trusted-host files.pythonhosted.org
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]

#build&run
#docker build --tag python-docker .
#docker run -d -p 5000:5000 python-docker