FROM golang:1.16-buster AS build
WORKDIR /go-build

COPY . .
RUN go mod download
COPY *.go ./
RUN go build -o /compiled

FROM gcr.io/distroless/base-debian10

WORKDIR /go-run

COPY --from=build /compiled /compiled
EXPOSE 8080
ENTRYPOINT ["/compiled"]

#build&run
#docker build --tag go-docker .
#docker run -d -p 8080:8080 go-docker
